# Netlify deployment configuration
[build]
  command = "npm run build"
  publish = "out"

# Note: Static export doesn't need @netlify/plugin-nextjs
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://esp32-flash-api.your-domain.workers.dev"

# Headers for WebSerial API
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    
# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200