name = "esp32-flash-api"
main = "src/index.ts"
compatibility_date = "2024-10-16"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "esp32-flash-keys"
database_id = "f34bc437-e514-44f6-8c80-98a6d306c594"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
ALLOWED_ORIGINS = "https://minizjp.com,https://www.minizjp.com"

# Development environment
[env.development]
name = "esp32-flash-api-dev"

[env.development.vars]
ENVIRONMENT = "development" 
ALLOWED_ORIGINS = "http://localhost:3000"